apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: demo
  labels:
    app: payment-api
spec:
  type: NodePort
  selector:
    app: payment-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30080
